import { AppBar, Toolbar, Typography, Button, Container } from '@mui/material'
// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import ResponsiveAppBar from '../components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container maxWidth="xl">
          <ResponsiveAppBar />
          {children}
        </Container>
      </body>
    </html>
  )
}
